apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: nginx
      labels:
        app: myapp
        tier: frontend
        env: dev
    spec:
      containers: 
      - name: nginx
        image: nginx
    